[package]
name = "cli-clap"
version = "0.0.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.5.26", features = ["derive"] }
uuid = { version = "=1.12.0", features = ["v4"]}
